name: "Analyzer"

on:
  workflow_call:

jobs:
  analyzer:
    strategy:
      matrix:
        sdk: [ stable ]
        os: [ ubuntu-latest ]

    name: "Code Analyzer"
    runs-on: ${{ matrix.os }}

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4.2.2

      - name: "Setup Dart SDK"
        if: success()
        uses: dart-lang/setup-dart@v1.6.5
        with:
          sdk: ${{ matrix.sdk }}

      - name: "Enable Derry"
        if: success()
        run: dart pub global activate derry || false

      - name: "Run Analyzer"
        if: success()
        run: |
          derry update || false
          derry analyze || false
